name: Auto labeler
on:
    issues:
        types: [ opened, edited, milestoned ]
    pull_request_target:
        types: [ opened ]
permissions:
    # Setting up permissions in the workflow to limit the scope of what it can do. Optional!
    contents: read
    issues: write
    pull-requests: write
    statuses: write
    checks: write
jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
            -   name: Check Labels
                id: labeler
                uses: fuxingloh/multi-labeler@v1
                with:
                    github-token: ${{secrets.GITHUB_TOKEN}}
