name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Dependabot auto-merge
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
            ref: ${{ github.ref }}
            #If you would like to wait for all other checks to complete you may set running-workflow-name to the name of the current job and not set a check-name parameter.
            running-workflow-name: 'Dependabot auto-merge'
            repo-token: ${{ secrets.PR_TOKEN }}
            wait-interval: 10
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.3
        with:
          github-token: "${{ secrets.PR_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: |
            gh pr review --approve "$PR_URL"
            gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.PR_TOKEN}}
