name: Release Drafter Fiberzap
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'fiberzap/**'
jobs:
    draft_release_fiberzap:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-fiberzap.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
---
name: Release Drafter Opafiber
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'opafiber/**'
jobs:
    draft_release_opafiber:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-opafiber.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
---
name: Release Drafter Otelfiber
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'otelfiber/**'
jobs:
    draft_release_otelfiber:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-otelfiber.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
---
name: Release Drafter Paseto
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'paseto/**'
jobs:
    draft_release_paseto:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-paseto.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
---
name: Release Drafter Swagger
on:
    push:
        # branches to consider in the event; optional, defaults to all
        branches:
            - master
            - main
        paths:
            - 'swagger/**'
jobs:
    draft_release_swagger:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            -   uses: release-drafter/release-drafter@v5
                with:
                    config-name: release-drafter-swagger.yml
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
