'on':
  - push
  - pull_request
name: Tests
jobs:
  Tests:
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
        platform:
          - ubuntu-latest
          - windows-latest
    runs-on: '${{ matrix.platform }}'
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Test PASETO Middleware
        run: cd ./paseto && go test ./... -v -race
      - name: Test Fiberzap Middleware
        run: cd ./fiberzap && go test ./... -v -race
